### ISSUE TITLE
Introducción

### ISSUE THREAD

**Issue by albagonma** [rfaromero12/IW-practicas#12]

**Comment by i82rusam** [comment]
Quiénes somos

Este proyecto lo formamos seis estudiantes de Ingeniería Informática de la rama de Software en la Universidad de Córdoba, nuestros nombres son:

      Jesús Arjona Carrillo
      Alba González Maraver 
      Rafael Romero Pérez
      Marta Rubio Sánchez 
      Miguel Ángel Ruiz Fernández
      Francisco Ruiz Roldán


Introducción

El proyecto que estamos destinados a realizar, se basa principalmente en el diseño y desarrollo de una aplicación web muy útil. Estamos hablando de una aplicación para uso bancario la cual abre diversos caminos en el nicho bancario y económico.

Principalmente queremos facilitar la utilización de la misma en las sucursales que la soliciten. Ésta ayuda a la utilización y organización económica de cada uno de los usuarios que la utilicen.

Nuestra idea es hacer que el sistema actual bancario mejore gracias a esta aplicación, con el fin de simplificar y hacer de una manera más fácil todas las acciones que se requieran. Como por ejemplo: Transferencias, transacciones, pagos mediante internet, ingresos o retiradas de dinero de forma más sencilla.

Cada cliente podrá disponer de un usuario dentro de nuestra aplicación a través del cual podrá realizar cualquiera de las acciones mencionadas anteriormente.

Los primeros pasos a seguir será observar nuestra competencia para ver cómo podríamos mejorar nuestro sistema en comparación con los demás, lo especificaremos más adelante.
